# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
#              "you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, "
#              "you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]
question_data =  [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "There are 86400 seconds in a day.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "What is the chemical makeup of water?", "correct_answer": "H20",
     "incorrect_answers": ["C12H6O2", "CO2", "H"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What is the Swedish word for &quot;window&quot;?", "correct_answer": "F&ouml;nster",
     "incorrect_answers": ["H&aring;l", "Sk&auml;rm", "Ruta"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "In the game &quot;Overwatch,&quot; which quote does the hero &quot;McCree&quot; NOT say upon using his flashbang ability?",
     "correct_answer": "&quot;You done?&quot;",
     "incorrect_answers": ["&quot;Whoa there.&quot;", "&quot;Hold up now.&quot;", "&quot;Don&#039;t move.&quot;"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "Which of these Roman gods doesn&#039;t have a counterpart in Greek mythology?",
     "correct_answer": "Janus", "incorrect_answers": ["Vulcan", "Juno", "Mars"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In the anime Assassination Classroom what is the class that Korosensei teaches?",
     "correct_answer": "Class 3-E", "incorrect_answers": ["Class 3-A", "Class 3-B", "Class 3-D"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "In the Pok&eacute;mon series, what is Palkia&#039;s hidden ability?", "correct_answer": "Telepathy",
     "incorrect_answers": ["Pressure", "Water Bubble", "Hydration"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "In &quot;The Binding of Isaac&quot;, which item instantly kills Mom and Mom&#039;s Heart?",
     "correct_answer": "The Bible", "incorrect_answers": ["The Halo", "Brimstone", "Book of Shadows"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In &quot;Highschool DxD&quot;, what is the name of the item some humans are born with?",
     "correct_answer": "Sacred Gear", "incorrect_answers": ["Imperial Arm", "Hallowed Relic", "Blessed Artifact"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
     "incorrect_answers": ["False"]}]
